// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT4Ss1AJA-HPs1ZgMZWoGHSMzqd25nhPI',
    appId: '1:106716720320:web:1c1ef364b41456a9829125',
    messagingSenderId: '106716720320',
    projectId: 'realtime-quizzes-db217',
    authDomain: 'realtime-quizzes-db217.firebaseapp.com',
    storageBucket: 'realtime-quizzes-db217.firebasestorage.app',
    measurementId: 'G-X8RDEG9VH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeLoz8899lfMH8ZKOp4xRhIyTPV-BEGTk',
    appId: '1:106716720320:android:6e1e626a766490fe829125',
    messagingSenderId: '106716720320',
    projectId: 'realtime-quizzes-db217',
    storageBucket: 'realtime-quizzes-db217.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLjpXKUjRwRJhyPrgxr46WffiR-coOwLU',
    appId: '1:106716720320:ios:3fb3b750274a0f1f829125',
    messagingSenderId: '106716720320',
    projectId: 'realtime-quizzes-db217',
    storageBucket: 'realtime-quizzes-db217.firebasestorage.app',
    iosBundleId: 'com.example.realtimeQuizzes',
  );
}
